config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # create
  get "articles/new", to: "articles#new"

  get "articles", to: "articles#index"
  post "articles", to: "articles#create"

  get "articles/:id", to: "articles#show", as: "article"
  patch "articles/:id", to: "articles#update"
  delete "articles/:id", to: "articles#destroy"

  get "article/:id/edit", to: "articles#edit" , as: "article-edit"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save

    redirect_to article_path(@article.id)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to article_path(@article.id)
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="container w-50">
  <h1>Update a Article</h1>
  <%= simple_form_for(@article) do |f| %>
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.submit %>
  <% end %>
</div>

app/views/articles/index.html.erb
<div class="container w-50">
  <h1>All Articles</h1>
  <% @articles.each do |article| %>
    <div class="article">
      <%= link_to "#{article.title}", article_path(article.id), class: "article-title" %>
      <%= link_to "delete", article_path(article.id), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-primary" %>
    </div>
  <% end %>

  <h3> <%= link_to "Create a new Article", articles_new_path %> </h3>
</div>

app/views/articles/new.html.erb
<%= form_for(@article) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :content %>
  <%= t.text_field :content %>
  <%= t.submit %>
<% end %>

app/views/articles/show.html.erb
<h1> <%= @article.title %> </h1>
<h3> <%= @article.content %> </h3>

<%= link_to "homepage", articles_path %>
<%= link_to "Update post", article_edit_path(@article.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>